---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gameoflife-deploy
  labels:
    app: gameoflife
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gameoflife
      version: "1.0"
  template:
    metadata:
      labels:
        app: gameoflife
        version: "1.0"
    spec:
      containers:
        - image: veerendradevops/gameoflife:latest
          name: gol-dev
          ports:
            - containerPort: 8080
              protocol: TCP 

---
apiVersion: v1
kind: Service
metadata:
  name: gol-dev
spec:
  type: NodePort
  selector:
    app: gameoflife
  ports:
    - targetPort: 8080
      port: 8080